# Generated by Django 5.0.6 on 2024-05-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Completed',
            new_name='is_completed',
        ),
    ]
